spring.application.name=Intranet
spring.datasource.url=jdbc:postgresql://localhost:5432/walletto
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


spring.mvc.hiddenmethod.filter.enabled=true


#For Devtools
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# location with user avatars
upload.path=C:/Users/Daniils/IdeaProjects/Intranet/uploads/userAvatars
#upload.path=/home/dandek/IdeaProjects/Intranet/uploads

# session time
server.servlet.session.timeout=9h